import { query } from '../../config/database.js';
import { deleteFiles, extractStoragePath, STORAGE_BUCKET } from '../../config/storage.js';

export type DeletionJobKind = 'course' | 'user';

const STORAGE_DELETE_BATCH_SIZE = 100;
const STORAGE_ITEM_LEASE_SECONDS = 10 * 60;
const STORAGE_DISCOVERY_BATCH_SIZE = 500;

type StorageItemRow = {
  id: string;
  storage_path: string;
};

type StorageScanCursorRow = {
  last_storage_path: string | null;
  completed_at: Date | null;
};

function isSafeStoragePath(path: string): boolean {
  return path.length <= 1200
    && !path.includes('..')
    && !/[<>"'`\\]/.test(path)
    && !path.startsWith('/')
    && !path.includes('//');
}

/** A cursor must only move forward; replaying an earlier page is safe but skipping one is not. */
export function shouldAdvanceStorageScanCursor(current: string | null, next: string): boolean {
  return current === null || next > current;
}

/**
 * Convert legacy public URLs to object keys and reject paths outside the
 * tenant prefix. A deletion worker must never follow an arbitrary URL.
 */
export function normalizeTenantStoragePath(value: unknown, tenantId: string): string | null {
  if (typeof value !== 'string') return null;
  const raw = value.trim();
  if (!raw) return null;
  const path = extractStoragePath(raw);
  if (!path || !isSafeStoragePath(path)) return null;
  return path.startsWith(`${tenantId}/`) ? path : null;
}

export async function registerStorageManifestPaths(
  jobKind: DeletionJobKind,
  jobId: string,
  tenantId: string,
  rawPaths: readonly string[],
): Promise<number> {
  const paths = [...new Set(rawPaths
    .map((path) => normalizeTenantStoragePath(path, tenantId))
    .filter((path): path is string => path !== null))];
  if (paths.length === 0) return 0;

  const result = await query(
    `INSERT INTO deletion_storage_items (job_kind, job_id, tenant_id, storage_path)
     SELECT $1::varchar, $2::uuid, $3::uuid, path
     FROM unnest($4::text[]) AS path
     ON CONFLICT (job_kind, job_id, storage_path) DO NOTHING`,
    [jobKind, jobId, tenantId, paths],
  );
  return result.rowCount || 0;
}

async function getOrCreateStorageScanCursor(
  jobKind: DeletionJobKind,
  jobId: string,
  tenantId: string,
  prefix: string,
): Promise<StorageScanCursorRow> {
  await query(
    `INSERT INTO deletion_storage_scan_cursors (job_kind, job_id, tenant_id, prefix)
     VALUES ($1::varchar, $2::uuid, $3::uuid, $4::text)
     ON CONFLICT (job_kind, job_id, prefix) DO NOTHING`,
    [jobKind, jobId, tenantId, prefix],
  );
  const result = await query<StorageScanCursorRow>(
    `SELECT last_storage_path, completed_at
     FROM deletion_storage_scan_cursors
     WHERE job_kind = $1::varchar AND job_id = $2::uuid AND prefix = $3::text`,
    [jobKind, jobId, prefix],
  );
  const cursor = result.rows[0];
  if (!cursor) throw new Error('Unable to create durable storage scan cursor');
  return cursor;
}

async function advanceStorageScanCursor(
  jobKind: DeletionJobKind,
  jobId: string,
  prefix: string,
  lastStoragePath: string,
): Promise<void> {
  await query(
    `UPDATE deletion_storage_scan_cursors
     SET last_storage_path = $4::text, updated_at = now()
     WHERE job_kind = $1::varchar
       AND job_id = $2::uuid
       AND prefix = $3::text
       AND (last_storage_path IS NULL OR last_storage_path < $4::text)`,
    [jobKind, jobId, prefix, lastStoragePath],
  );
}

async function markStorageScanCursorCompleted(
  jobKind: DeletionJobKind,
  jobId: string,
  prefix: string,
): Promise<void> {
  await query(
    `UPDATE deletion_storage_scan_cursors
     SET completed_at = now(), updated_at = now()
     WHERE job_kind = $1::varchar AND job_id = $2::uuid AND prefix = $3::text`,
    [jobKind, jobId, prefix],
  );
}

/**
 * Discover objects directly from Supabase's storage catalog before deleting a
 * subject.  DB references alone are not an ownership boundary: an upload may
 * have reached Storage before its application transaction failed.  Prefixes
 * passed here are generated by the server, must stay within one tenant, and
 * are read in a keyset-paginated way so very large courses remain bounded.
 */
export async function registerStoragePrefixManifestPaths(
  jobKind: DeletionJobKind,
  jobId: string,
  tenantId: string,
  prefix: string,
): Promise<number> {
  const normalizedPrefix = normalizeTenantStoragePath(prefix, tenantId);
  if (!normalizedPrefix || !normalizedPrefix.endsWith('/')) {
    throw new Error('Unsafe storage prefix blocked deletion discovery');
  }

  const cursor = await getOrCreateStorageScanCursor(jobKind, jobId, tenantId, normalizedPrefix);
  if (cursor.completed_at) return 0;

  let after = cursor.last_storage_path || '';
  let registered = 0;
  while (true) {
    const result = await query<{ storage_path: string }>(
      `SELECT name AS storage_path
       FROM storage.objects
       WHERE bucket_id = $1
         AND name LIKE $2 || '%'
         AND ($3 = '' OR name > $3)
       ORDER BY name ASC
       LIMIT $4::int`,
      [STORAGE_BUCKET, normalizedPrefix, after, STORAGE_DISCOVERY_BATCH_SIZE],
    );
    if (result.rowCount === 0) {
      await markStorageScanCursorCompleted(jobKind, jobId, normalizedPrefix);
      return registered;
    }

    registered += await registerStorageManifestPaths(
      jobKind,
      jobId,
      tenantId,
      result.rows.map((row) => row.storage_path),
    );
    after = result.rows[result.rows.length - 1].storage_path;
    // The manifest insert commits before the cursor advances. A crash can only
    // repeat a page (deduplicated by the manifest key), never skip an object.
    await advanceStorageScanCursor(jobKind, jobId, normalizedPrefix, after);
  }
}

async function claimStorageItems(jobKind: DeletionJobKind, jobId: string): Promise<StorageItemRow[]> {
  const result = await query<StorageItemRow>(
    `WITH expired AS (
       UPDATE deletion_storage_items
       SET status = 'pending', lease_expires_at = NULL, updated_at = now()
       WHERE job_kind = $1::varchar
         AND job_id = $2::uuid
         AND status = 'running'
         AND lease_expires_at < now()
     ),
     picked AS (
       SELECT id
       FROM deletion_storage_items
       WHERE job_kind = $1::varchar
         AND job_id = $2::uuid
         AND status = 'pending'
       ORDER BY id
       LIMIT $3::int
       FOR UPDATE SKIP LOCKED
     )
     UPDATE deletion_storage_items item
     SET status = 'running',
         attempts = item.attempts + 1,
         lease_expires_at = now() + ($4::int * interval '1 second'),
         updated_at = now(),
         last_error = NULL
     FROM picked
     WHERE item.id = picked.id
     RETURNING item.id, item.storage_path`,
    [jobKind, jobId, STORAGE_DELETE_BATCH_SIZE, STORAGE_ITEM_LEASE_SECONDS],
  );
  return result.rows;
}

async function markStorageItemsSucceeded(ids: readonly string[]): Promise<void> {
  if (ids.length === 0) return;
  await query(
    `UPDATE deletion_storage_items
     SET status = 'succeeded', lease_expires_at = NULL, last_error = NULL, updated_at = now()
     WHERE id = ANY($1::uuid[])`,
    [ids],
  );
}

async function releaseStorageItems(ids: readonly string[], error: unknown): Promise<void> {
  if (ids.length === 0) return;
  const message = error instanceof Error ? error.message : String(error);
  await query(
    `UPDATE deletion_storage_items
     SET status = 'pending', lease_expires_at = NULL, last_error = $2, updated_at = now()
     WHERE id = ANY($1::uuid[])`,
    [ids, message.slice(0, 4000)],
  );
}

/**
 * Drain the persistent manifest. The storage call happens before a row is
 * marked succeeded; a process crash merely repeats a safe, idempotent remove.
 */
export async function deleteStorageManifest(jobKind: DeletionJobKind, jobId: string): Promise<number> {
  let deleted = 0;
  while (true) {
    const items = await claimStorageItems(jobKind, jobId);
    if (items.length === 0) return deleted;

    try {
      await deleteFiles(items.map((item) => item.storage_path));
      await markStorageItemsSucceeded(items.map((item) => item.id));
      deleted += items.length;
    } catch (error) {
      await releaseStorageItems(items.map((item) => item.id), error).catch(() => undefined);
      throw error;
    }
  }
}

export async function countUnfinishedStorageManifestItems(jobKind: DeletionJobKind, jobId: string): Promise<number> {
  const result = await query<{ count: string }>(
    `SELECT count(*)::text AS count
     FROM deletion_storage_items
     WHERE job_kind = $1::varchar
       AND job_id = $2::uuid
       AND status <> 'succeeded'`,
    [jobKind, jobId],
  );
  return Number(result.rows[0]?.count || 0);
}
