const MB = 1024 * 1024;

export const COURSE_ASSET_MAX_UPLOAD_MB = 300;
export const COURSE_ASSET_MAX_UPLOAD_BYTES = COURSE_ASSET_MAX_UPLOAD_MB * MB;
export const COURSE_ASSET_MAX_UPLOAD_LABEL = `${COURSE_ASSET_MAX_UPLOAD_MB}MB`;
