import type {
  LessonAuthorIntentOperation,
  LessonAuthorIntentPlan,
  LessonAuthorTargetType,
} from './lesson-author-intent.logic.js';

export type LessonAuthorEditorEntityType = NonNullable<LessonAuthorTargetType>;
export type LessonAuthorTargetSource =
  | 'mention'
  | 'editor_context'
  | 'explicit_reference'
  | 'conversation_context'
  | 'none';

export interface LessonAuthorEditorContextInput {
  course_id: string;
  selected_entity?: {
    id: string;
    type: LessonAuthorEditorEntityType;
    block_type?: string;
  };
  current_chapter_id?: string;
  current_lesson_id?: string;
  current_unit_id?: string;
  current_component_id?: string;
}

export interface ResolvedLessonAuthorEditorEntity {
  id: string;
  type: LessonAuthorEditorEntityType;
  parent_id: string | null;
  ancestor_ids: string[];
}

export interface ValidatedLessonAuthorEditorContext extends LessonAuthorEditorContextInput {
  selected_entity?: LessonAuthorEditorContextInput['selected_entity'];
}

export type LessonAuthorCommandIntent =
  | 'ANSWER'
  | 'GENERATE_COURSE'
  | 'CREATE'
  | 'UPDATE_CONTENT'
  | 'RENAME'
  | 'DELETE'
  | 'MOVE'
  | 'CLARIFY';

export type LessonAuthorCommandScope =
  | 'CURRENT_ENTITY'
  | 'CURRENT_UNIT'
  | 'CURRENT_LESSON'
  | 'CURRENT_CHAPTER'
  | 'FULL_COURSE'
  | 'UNRESOLVED';

export type LessonAuthorSourceMode = 'NONE' | 'RELEVANT_SOURCE' | 'FULL_SOURCE';

export interface NormalizedLessonAuthorCommand {
  version: 1;
  intent: LessonAuthorCommandIntent;
  operation: LessonAuthorIntentOperation;
  target: {
    type: LessonAuthorTargetType;
    id: string | null;
    parent_id: string | null;
    source: LessonAuthorTargetSource;
  };
  scope: LessonAuthorCommandScope;
  source_mode: LessonAuthorSourceMode;
  route: 'deterministic';
  user_instruction: string;
  requested_fields: LessonAuthorIntentPlan['fields'];
  source_document_ids: string[];
  confidence: number;
  clarification_required: boolean;
}

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
// Course records use the Open edX course key generated by
// course-authoring.controller.ts. UUIDs remain accepted for legacy course
// records, but the caller still has to exact-match this value to the
// conversation course and resolve it through the tenant-scoped course tree.
const COURSE_KEY_REGEX = /^course-v1:[^\s+]+(?:\+[^\s+]+){2,}$/i;
const ENTITY_TYPES = new Set<LessonAuthorEditorEntityType>(['course', 'chapter', 'lesson', 'unit', 'component']);

function readUuid(value: unknown, field: string): string | undefined {
  if (value === undefined || value === null) return undefined;
  if (typeof value !== 'string' || !UUID_REGEX.test(value.trim())) {
    throw new Error(`${field} không hợp lệ.`);
  }
  return value.trim();
}

function readCourseId(value: unknown, field: string): string | undefined {
  if (value === undefined || value === null) return undefined;
  if (typeof value !== 'string') throw new Error(`${field} không hợp lệ.`);
  const normalized = value.trim();
  if (!UUID_REGEX.test(normalized) && !COURSE_KEY_REGEX.test(normalized)) {
    throw new Error(`${field} không hợp lệ.`);
  }
  return normalized;
}

function readEntityType(value: unknown, field: string): LessonAuthorEditorEntityType {
  if (typeof value !== 'string' || !ENTITY_TYPES.has(value as LessonAuthorEditorEntityType)) {
    throw new Error(`${field} không hợp lệ.`);
  }
  return value as LessonAuthorEditorEntityType;
}

/**
 * Parse the browser contract only. The caller must still resolve every ID
 * against the tenant/course tree before using it as an AI target.
 */
export function normalizeLessonAuthorEditorContext(value: unknown): LessonAuthorEditorContextInput | null {
  if (value === undefined || value === null) return null;
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('editor_context không hợp lệ.');
  }
  const record = value as Record<string, unknown>;
  const courseId = readCourseId(record.course_id, 'editor_context.course_id');
  if (!courseId) throw new Error('editor_context.course_id không hợp lệ.');

  let selectedEntity: LessonAuthorEditorContextInput['selected_entity'];
  if (record.selected_entity !== undefined && record.selected_entity !== null) {
    if (!record.selected_entity || typeof record.selected_entity !== 'object' || Array.isArray(record.selected_entity)) {
      throw new Error('editor_context.selected_entity không hợp lệ.');
    }
    const selected = record.selected_entity as Record<string, unknown>;
    const id = readUuid(selected.id, 'editor_context.selected_entity.id');
    if (!id) throw new Error('editor_context.selected_entity.id không hợp lệ.');
    const type = readEntityType(selected.type, 'editor_context.selected_entity.type');
    const blockType = typeof selected.block_type === 'string' && selected.block_type.trim()
      ? selected.block_type.trim().slice(0, 50)
      : undefined;
    selectedEntity = { id, type, ...(blockType ? { block_type: blockType } : {}) };
  }

  return {
    course_id: courseId,
    ...(selectedEntity ? { selected_entity: selectedEntity } : {}),
    ...(readUuid(record.current_chapter_id, 'editor_context.current_chapter_id') ? { current_chapter_id: readUuid(record.current_chapter_id, 'editor_context.current_chapter_id') } : {}),
    ...(readUuid(record.current_lesson_id, 'editor_context.current_lesson_id') ? { current_lesson_id: readUuid(record.current_lesson_id, 'editor_context.current_lesson_id') } : {}),
    ...(readUuid(record.current_unit_id, 'editor_context.current_unit_id') ? { current_unit_id: readUuid(record.current_unit_id, 'editor_context.current_unit_id') } : {}),
    ...(readUuid(record.current_component_id, 'editor_context.current_component_id') ? { current_component_id: readUuid(record.current_component_id, 'editor_context.current_component_id') } : {}),
  };
}

/**
 * Validate type declarations and that every supplied hierarchy field is the
 * selected entity itself or one of its server-resolved ancestors. This is pure
 * so the database adapter can be tested independently from the chat flow.
 */
export function validateResolvedLessonAuthorEditorContext(
  context: LessonAuthorEditorContextInput,
  expectedCourseId: string,
  entities: ReadonlyMap<string, ResolvedLessonAuthorEditorEntity>,
): ValidatedLessonAuthorEditorContext {
  if (context.course_id !== expectedCourseId) {
    throw new Error('editor_context không thuộc khóa học của cuộc hội thoại.');
  }

  const expectedFields: Array<[keyof Pick<LessonAuthorEditorContextInput,
    'current_chapter_id' | 'current_lesson_id' | 'current_unit_id' | 'current_component_id'>,
    LessonAuthorEditorEntityType]> = [
    ['current_chapter_id', 'chapter'],
    ['current_lesson_id', 'lesson'],
    ['current_unit_id', 'unit'],
    ['current_component_id', 'component'],
  ];
  for (const [field, type] of expectedFields) {
    const id = context[field];
    if (!id) continue;
    const entity = entities.get(id);
    if (!entity || entity.type !== type) {
      throw new Error(`${field} không thuộc đúng cấp outline của khóa học.`);
    }
  }

  if (!context.selected_entity) return context;
  const selected = entities.get(context.selected_entity.id);
  if (!selected || selected.type !== context.selected_entity.type) {
    throw new Error('selected_entity không thuộc đúng loại target của khóa học.');
  }

  const selectedLineage = new Set([selected.id, ...selected.ancestor_ids]);
  for (const [field] of expectedFields) {
    const id = context[field];
    if (id && !selectedLineage.has(id)) {
      throw new Error('editor_context không đúng quan hệ phân cấp của outline.');
    }
  }
  return context;
}

function hasDeicticTargetReference(value: string): boolean {
  return /(^|\s)(?:cái này|node này|phần này|mục này|bài này|bài học này|chương này|component này|section này|unit này|this|current|selected)(?:\s|$)/iu.test(value.trim());
}

function hasExplicitTargetIdentifier(value: string): boolean {
  return /(?:chương|chuong|chapter|mục|muc|section|module|sequential|bài học|bai hoc|lesson|unit|vertical)\s*(?:số\s*)?\d+(?:\.\d+){0,2}/iu.test(value);
}

export function selectEditorContextTarget(
  userInstruction: string,
  preliminaryPlan: LessonAuthorIntentPlan,
  editorContext: ValidatedLessonAuthorEditorContext | null,
  hasExplicitMention: boolean,
): { id: string; type: LessonAuthorEditorEntityType } | null {
  if (!editorContext || hasExplicitMention || hasExplicitTargetIdentifier(userInstruction)) return null;
  if (!hasDeicticTargetReference(userInstruction)) return null;
  if (preliminaryPlan.operation === 'course_blueprint') return null;

  const byType: Partial<Record<LessonAuthorEditorEntityType, string | undefined>> = {
    chapter: editorContext.current_chapter_id,
    lesson: editorContext.current_lesson_id,
    unit: editorContext.current_unit_id,
    component: editorContext.current_component_id,
  };
  const requestedType = preliminaryPlan.target_type;
  if (requestedType && requestedType !== 'course') {
    const id = byType[requestedType];
    return id ? { id, type: requestedType } : null;
  }
  const selected = editorContext.selected_entity;
  return selected ? { id: selected.id, type: selected.type } : null;
}

function commandIntent(operation: LessonAuthorIntentOperation): LessonAuthorCommandIntent {
  switch (operation) {
    case 'course_blueprint': return 'GENERATE_COURSE';
    case 'create': return 'CREATE';
    case 'update_content': return 'UPDATE_CONTENT';
    case 'rename': return 'RENAME';
    case 'delete': return 'DELETE';
    case 'move': return 'MOVE';
    case 'clarify': return 'CLARIFY';
    default: return 'ANSWER';
  }
}

function commandScope(plan: LessonAuthorIntentPlan): LessonAuthorCommandScope {
  if (plan.operation === 'course_blueprint' || plan.target_type === 'course') return 'FULL_COURSE';
  if (!plan.target_type) return 'UNRESOLVED';
  if (plan.target_type === 'chapter') return 'CURRENT_CHAPTER';
  if (plan.target_type === 'lesson') return 'CURRENT_LESSON';
  if (plan.target_type === 'unit') return 'CURRENT_UNIT';
  return 'CURRENT_ENTITY';
}

export function buildNormalizedLessonAuthorCommand(input: {
  plan: LessonAuthorIntentPlan;
  userInstruction: string;
  sourceDocumentIds: string[];
}): NormalizedLessonAuthorCommand {
  const sourceDocumentIds = [...new Set(input.sourceDocumentIds.filter(Boolean))];
  const sourceMode: LessonAuthorSourceMode = sourceDocumentIds.length === 0
    ? 'NONE'
    : input.plan.operation === 'course_blueprint'
      ? 'FULL_SOURCE'
      : 'RELEVANT_SOURCE';
  return {
    version: 1,
    intent: commandIntent(input.plan.operation),
    operation: input.plan.operation,
    target: {
      type: input.plan.target_type,
      id: input.plan.target_block_id ?? null,
      parent_id: input.plan.target_resolution === 'new' ? input.plan.target_block_id ?? null : null,
      source: input.plan.target_source as LessonAuthorTargetSource,
    },
    scope: commandScope(input.plan),
    source_mode: sourceMode,
    route: 'deterministic',
    user_instruction: input.userInstruction,
    requested_fields: input.plan.fields,
    source_document_ids: sourceDocumentIds,
    confidence: input.plan.confidence,
    clarification_required: input.plan.operation === 'clarify' || input.plan.requires_confirmation,
  };
}

export function isSimpleDeterministicLessonAuthorCommand(command: NormalizedLessonAuthorCommand): boolean {
  return command.intent === 'RENAME' || command.intent === 'DELETE' || command.intent === 'MOVE';
}
